name: Release Gem to RubyGems.org

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    name: Build and Publish Package to RubyGems.org
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby 3.4.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.7

      - name: Check release validity
        run: sh .github/scripts/check-release.sh

      - name: Publish to RubyGems
        env:
          GEM_HOST_API_KEY: ${{secrets.RUBYGEMS_AUTH_TOKEN}}
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build phlex-icons.gemspec
          gem push *.gem
