name: Release icon pack specific gem to RubyGems.org

on:
  workflow_call:
    inputs:
      pack_name:
        description: 'The name of the icon pack'
        required: true

jobs:
  build-and-publish:
    name: Build and Publish Package to RubyGems.org
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby 3.3.4
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.4

      - name: Check release validity
        run: sh .github/scripts/check-release.sh

      - name: Prepare icon pack specific gem
        run: sh .github/scripts/prepare-new-gem.sh ${{ inputs.pack_name }}

      - name: Publish to RubyGems
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_AUTH_TOKEN }}
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gemspec_file="phlex-icons-${{ inputs.pack_name }}.gemspec"
          gem build "$gemspec_file"
          gem push *.gem
